// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niuyemyqnrznhdrjfbnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pdXllbXlxbnJ6bmhkcmpmYm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTkzNjAsImV4cCI6MjA2MTI5NTM2MH0.gbAIit_f6rqFwl8BfKllBhTEyWPZzFf-YxEh7FpSerA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);